import { beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({session:vi.fn(),csrf:vi.fn(),campaign:vi.fn(),paid:vi.fn(),flag:vi.fn(),resolve:vi.fn()}));
vi.mock("@/lib/auth/server",()=>({currentAdminSession:mocks.session,assertSessionCsrf:mocks.csrf}));
vi.mock("@/lib/runtime/production-actions",()=>({saveCampaign:mocks.campaign,markPayoutPaid:mocks.paid,createFraudFlag:mocks.flag,resolveFraudFlag:mocks.resolve}));
import { POST } from "@/app/admin/actions/route";
const csrf="synthetic-csrf";
function request(fields:Record<string,string>,origin="https://refer.ph7.health"){return new Request("https://refer.ph7.health/admin/actions",{method:"POST",headers:{origin,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({csrfToken:csrf,...fields})});}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("NODE_ENV","production");mocks.session.mockResolvedValue({kind:"ADMIN",adminUserId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",adminRole:"FOUNDER"});});
describe("founder admin mutation boundary",()=>{
  it("rejects unauthorised and cross-site requests before domain actions",async()=>{mocks.session.mockResolvedValue(null);expect((await POST(request({action:"campaign.save"}))).status).toBe(403);expect(mocks.campaign).not.toHaveBeenCalled();mocks.session.mockResolvedValue({kind:"ADMIN",adminUserId:"a",adminRole:"FOUNDER"});expect((await POST(request({action:"campaign.save"},"https://evil.example"))).status).toBe(403);expect(mocks.campaign).not.toHaveBeenCalled();});
  it("requires CSRF and explicit financial confirmation",async()=>{mocks.csrf.mockImplementationOnce(()=>{throw new Error("csrf")});await POST(request({action:"payout.paid",payoutId:"33333333-3333-4333-8333-333333333333",confirmation:"MARK_PAID"}));expect(mocks.paid).not.toHaveBeenCalled();mocks.csrf.mockImplementation(()=>{});await POST(request({action:"payout.paid",payoutId:"33333333-3333-4333-8333-333333333333"}));expect(mocks.paid).not.toHaveBeenCalled();});
  it("delegates confirmed campaign and payout operations to the existing service path",async()=>{mocks.csrf.mockImplementation(()=>{});let response=await POST(request({action:"campaign.save",friendIncentiveMinor:"1500",referrerRewardMinor:"2000",holdingPeriodDays:"14",active:"true",confirmation:"SAVE_CAMPAIGN"}));expect(response.status).toBe(303);expect(mocks.campaign).toHaveBeenCalledWith(expect.objectContaining({role:"FOUNDER"}),{friendIncentiveMinor:1500,referrerRewardMinor:2000,holdingPeriodDays:14,active:true});response=await POST(request({action:"payout.paid",payoutId:"33333333-3333-4333-8333-333333333333",confirmation:"MARK_PAID"}));expect(response.status).toBe(303);expect(mocks.paid).toHaveBeenCalledWith(expect.anything(),"33333333-3333-4333-8333-333333333333","admin:payout:paid:33333333-3333-4333-8333-333333333333");});
});
