import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { FounderDashboard } from "@/components/admin/founder-dashboard";
import type { FounderDashboardData } from "@/lib/admin/data";

const now=new Date("2026-10-03T12:00:00.000Z");
const campaign={id:"11111111-1111-4111-8111-111111111111",version:2,name:"Referral programme v2",active:true,startsAt:null,endsAt:null,friendIncentiveMinor:1500,referrerRewardMinor:2000,holdingPeriodDays:14,qualificationEvent:"consultation.paid",createdAt:now};
const referral={id:"22222222-2222-4222-8222-222222222222",publicAttributionId:"attr_synthetic_public",referrerReference:"Referrer •••123456",referredReference:"Friend •••654321",campaignId:campaign.id,campaignVersion:2,friendIncentiveMinor:1500,referrerRewardMinor:2000,status:"QUALIFIED" as const,createdAt:now,qualifiedAt:now,payoutStatus:null,fraudStatus:null};
const data:FounderDashboardData={overview:{totalReferrals:1,newReferrals:1,previousNewReferrals:0,qualifiedReferrals:1,conversionRate:1,pendingRewardsMinor:0,availableRewardsMinor:2000,paidOutMinor:0,outstandingPayouts:1,openFraudFlags:1},programme:{enabled:true,minimumWithdrawalMinor:1000},activeCampaign:campaign,campaigns:[campaign],referrals:[referral],referralCount:1,referralPage:1,referralPages:1,selectedReferral:{...referral,events:[{id:"event",fromStatus:"PAID",toStatus:"QUALIFIED",source:"WEBHOOK",occurredAt:now}],ledger:[{id:"ledger",type:"CREDIT",amountMinor:2000,status:"EFFECTIVE",createdAt:now}],flags:[]},payouts:[{id:"33333333-3333-4333-8333-333333333333",referrerReference:"Patient •••123456",amountMinor:1000,status:"REQUESTED",accountMask:"•••• T154",requestedAt:now,paidAt:null,availableBalanceMinor:2000}],fraudFlags:[{id:"44444444-4444-4444-8444-444444444444",referralId:referral.id,type:"MANUAL_FLAG",status:"OPEN",detail:{reason:"Synthetic evidence"},createdAt:now,resolvedAt:null}],audit:[{id:"audit",actor:"Founder",action:"PROGRAMME_UPDATED",subjectType:"campaign",subjectId:campaign.id,beforeData:{friendIncentiveMinor:1000,referrerRewardMinor:1000},afterData:{friendIncentiveMinor:1500,referrerRewardMinor:2000},createdAt:now}],recentReferrals:[referral],recentPayouts:[]};

describe("production founder operations dashboard",()=>{
  it("renders authoritative overview and configured economics without invented revenue",()=>{const html=renderToStaticMarkup(<FounderDashboard data={data} tab="overview" csrfToken="synthetic-csrf" filters={{}}/>);expect(html).toContain("Programme health");expect(html).toContain("Give €15 · Get €20");expect(html).toContain("PostgreSQL ledger");expect(html).not.toContain("GMV");expect(html).not.toContain("CAC");});
  it("requires explicit confirmation for campaign and payout mutations",()=>{const campaignHtml=renderToStaticMarkup(<FounderDashboard data={data} tab="campaigns" csrfToken="synthetic-csrf" filters={{}}/>);expect(campaignHtml).toContain('value="SAVE_CAMPAIGN"');expect(campaignHtml).toContain('action="/admin/actions"');const payoutHtml=renderToStaticMarkup(<FounderDashboard data={data} tab="payouts" csrfToken="synthetic-csrf" filters={{}}/>);expect(payoutHtml).toContain('value="MARK_PAID"');expect(payoutHtml).toContain("manual transfer");expect(payoutHtml).toContain("•••• T154");});
  it("shows snapshots, lifecycle, ledger and safe audit metadata",()=>{const referrals=renderToStaticMarkup(<FounderDashboard data={data} tab="referrals" csrfToken="synthetic-csrf" filters={{}}/>);expect(referrals).toContain("€20 reward");expect(referrals).toContain("Lifecycle &amp; financial history");expect(referrals).toContain("WEBHOOK");const audit=renderToStaticMarkup(<FounderDashboard data={data} tab="audit" csrfToken="synthetic-csrf" filters={{}}/>);expect(audit).toContain("PROGRAMME UPDATED");expect(audit).not.toContain("password");expect(audit).not.toContain("IBAN");});
});
