import Link from "next/link";
import { Logo } from "@/components/logo";
import { formatEuro } from "@/lib/portal/format";
import type { FounderDashboardData, FounderFilters, FounderSection } from "@/lib/admin/data";
import { founderSections } from "@/lib/admin/data";

const labels:Record<FounderSection,string>={overview:"Overview",campaigns:"Campaigns",referrals:"Referrals",payouts:"Payouts",fraud:"Fraud",audit:"Audit"};
const stateLabels:Record<string,string>={ACTIVE:"Active",INACTIVE:"Inactive",VISITED:"Visited",ATTRIBUTED:"Attributed",REGISTERED:"Registered",BOOKED:"Booked",PAID:"Paid",QUALIFIED:"Qualified",PAYABLE:"Payable",PAID_OUT:"Paid out",CANCELLED:"Cancelled",REFUNDED:"Refunded",REJECTED:"Rejected",FRAUD_REVIEW:"Fraud review",EXPIRED:"Expired",REQUESTED:"Requested",OPEN:"Open",INVESTIGATING:"Investigating",APPROVED:"Approved"};
function displayState(value:string|null){return value?stateLabels[value]??value.replaceAll("_"," ").toLowerCase():"—"}
function stateTone(value:string|null){if(["ACTIVE","QUALIFIED","PAYABLE","PAID_OUT","PAID","APPROVED"].includes(value??""))return"positive";if(["FRAUD_REVIEW","OPEN","INVESTIGATING","REJECTED"].includes(value??""))return"review";if(["INACTIVE","CANCELLED","REFUNDED","EXPIRED"].includes(value??""))return"muted";return"neutral"}
function Status({value}:{value:string|null}){return <span className={`admin-status admin-status-${stateTone(value)}`}>{displayState(value)}</span>}
function when(value:Date|null,withTime=false){if(!value)return"—";return new Intl.DateTimeFormat("en-GB",withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}).format(value)}
function short(value:string|null){return value?value.slice(0,8):"system"}
function searchHref(tab:FounderSection,params:Record<string,string|number|undefined>={}){const query=new URLSearchParams({tab});for(const [key,value] of Object.entries(params))if(value!==undefined&&value!=="")query.set(key,String(value));return`/admin?${query}`}

export function FounderDashboard({data,tab,csrfToken,filters,result,error}:{data:FounderDashboardData;tab:FounderSection;csrfToken:string;filters:FounderFilters;result?:string;error?:string}){
  return <main className="founder-shell">
    <a className="admin-skip-link" href="#admin-main">Skip to content</a>
    <header className="founder-topbar"><Link className="founder-brand" href="/admin" aria-label="pH7 Refer founder dashboard"><Logo/><span>Refer</span></Link><div className="founder-account"><span className="admin-live-dot" aria-hidden="true"/>Production operations<form action="/admin/logout" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><button className="admin-link-button" type="submit">Sign out</button></form></div></header>
    <div className="founder-layout">
      <aside className="founder-sidebar"><p className="founder-sidebar-label">Founder console</p><nav aria-label="Founder operations">{founderSections.map(item=><Link key={item} href={searchHref(item)} className={item===tab?"active":""} aria-current={item===tab?"page":undefined}><span aria-hidden="true">{navIcon(item)}</span>{labels[item]}{item==="payouts"&&data.overview.outstandingPayouts>0?<b>{data.overview.outstandingPayouts}</b>:null}{item==="fraud"&&data.overview.openFraudFlags>0?<b>{data.overview.openFraudFlags}</b>:null}</Link>)}</nav><div className="founder-sidebar-note"><span>Financial source of truth</span><strong>PostgreSQL ledger</strong><small>Amounts shown in EUR minor units.</small></div></aside>
      <section className="founder-main" id="admin-main" tabIndex={-1}>
        {result?<div className="admin-notice admin-notice-success" role="status">{resultMessage(result)}</div>:null}
        {error?<div className="admin-notice admin-notice-error" role="alert">The operation could not be completed. No financial state was changed.</div>:null}
        {tab==="overview"?<Overview data={data}/>:null}
        {tab==="campaigns"?<Campaigns data={data} csrfToken={csrfToken}/>:null}
        {tab==="referrals"?<Referrals data={data} filters={filters} csrfToken={csrfToken}/>:null}
        {tab==="payouts"?<Payouts data={data} filters={filters} csrfToken={csrfToken}/>:null}
        {tab==="fraud"?<Fraud data={data} filters={filters} csrfToken={csrfToken}/>:null}
        {tab==="audit"?<Audit data={data} filters={filters}/>:null}
      </section>
    </div>
  </main>
}

function Header({eyebrow,title,copy,actions}:{eyebrow:string;title:string;copy:string;actions?:React.ReactNode}){return <header className="admin-page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{actions}</header>}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone?:string}){return <article className={`admin-metric ${tone?`admin-metric-${tone}`:""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function Overview({data}:{data:FounderDashboardData}){const o=data.overview;const delta=o.newReferrals-o.previousNewReferrals;return <>
  <Header eyebrow="Overview" title="Programme health" copy="Live referral, reward and payout operations from the authoritative database." actions={data.activeCampaign?<Link className="button button-soft admin-compact-button" href="/admin?tab=campaigns">Manage campaign</Link>:undefined}/>
  <div className="admin-metrics-grid"><Metric label="Total referrals" value={String(o.totalReferrals)} note={`${o.newReferrals} in the last 30 days (${delta>=0?"+":""}${delta} vs prior period)`}/><Metric label="Qualified referrals" value={String(o.qualifiedReferrals)} note={o.conversionRate===null?"No referrals yet":`${(o.conversionRate*100).toFixed(1)}% conversion`}/><Metric label="Available cash rewards" value={formatEuro(o.availableRewardsMinor)} note="Effective ledger balance" tone="green"/><Metric label="Pending cash rewards" value={formatEuro(o.pendingRewardsMinor)} note="Pending ledger credits"/><Metric label="Cash paid out" value={formatEuro(o.paidOutMinor)} note="Immutable payout debits"/><Metric label="Operations queue" value={String(o.outstandingPayouts+o.openFraudFlags)} note={`${o.outstandingPayouts} payouts · ${o.openFraudFlags} reviews`} tone={o.outstandingPayouts+o.openFraudFlags?"brown":undefined}/></div>
  <div className="admin-overview-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Live economics</p><h2>{data.activeCampaign?`Give ${formatEuro(data.activeCampaign.friendIncentiveMinor)} · Get ${formatEuro(data.activeCampaign.referrerRewardMinor)}`:"No active campaign"}</h2></div><Status value={data.activeCampaign?.active?"ACTIVE":"INACTIVE"}/></div>{data.activeCampaign?<dl className="admin-definition-grid"><div><dt>Campaign</dt><dd>{data.activeCampaign.name}</dd></div><div><dt>Version</dt><dd>{data.activeCampaign.version}</dd></div><div><dt>Qualification</dt><dd>{data.activeCampaign.qualificationEvent}</dd></div><div><dt>Holding period</dt><dd>{data.activeCampaign.holdingPeriodDays} days</dd></div><div><dt>Withdrawal minimum</dt><dd>{formatEuro(data.programme.minimumWithdrawalMinor)}</dd></div></dl>:<p className="admin-empty">New referral attribution is unavailable until an active campaign is configured.</p>}</section>
  <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Queue</p><h2>Needs attention</h2></div></div><Link className="admin-queue-row" href="/admin?tab=payouts"><span>Payout requests</span><strong>{o.outstandingPayouts}</strong></Link><Link className="admin-queue-row" href="/admin?tab=fraud"><span>Fraud / review</span><strong>{o.openFraudFlags}</strong></Link></section></div>
  <div className="admin-overview-grid"><RecentReferrals rows={data.recentReferrals}/><RecentPayouts rows={data.recentPayouts}/></div>
  </>}
function RecentReferrals({rows}:{rows:FounderDashboardData["recentReferrals"]}){return <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Latest</p><h2>Referral activity</h2></div><Link href="/admin?tab=referrals">View all</Link></div>{rows.length?rows.map(row=><Link className="admin-activity-row" key={row.id} href={searchHref("referrals",{referral:row.id})}><span><strong>{row.referredReference}</strong><small>{when(row.createdAt,true)}</small></span><Status value={row.status}/></Link>):<p className="admin-empty">No referral activity yet.</p>}</section>}
function RecentPayouts({rows}:{rows:FounderDashboardData["recentPayouts"]}){return <section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Latest</p><h2>Payout activity</h2></div><Link href="/admin?tab=payouts">View all</Link></div>{rows.length?rows.map(row=><div className="admin-activity-row" key={row.id}><span><strong>{formatEuro(row.amountMinor)}</strong><small>{row.referrerReference} · {when(row.requestedAt,true)}</small></span><Status value={row.status}/></div>):<p className="admin-empty">No payout activity yet.</p>}</section>}

function Campaigns({data,csrfToken}:{data:FounderDashboardData;csrfToken:string}){const active=data.activeCampaign;return <>
  <Header eyebrow="Campaigns" title="Referral economics" copy="Publish a new campaign version for future attributions. Historical snapshots and ledger entries never change."/>
  <div className="admin-campaign-layout"><section className="admin-panel admin-sticky-panel"><p className="eyebrow">Active offer</p>{active?<><h2>Give {formatEuro(active.friendIncentiveMinor)}.<br/>Get {formatEuro(active.referrerRewardMinor)} cash.</h2><Status value="ACTIVE"/><dl className="admin-definition-grid"><div><dt>Version</dt><dd>{active.version}</dd></div><div><dt>Holding</dt><dd>{active.holdingPeriodDays} days</dd></div><div><dt>Started</dt><dd>{when(active.startsAt??active.createdAt)}</dd></div><div><dt>Ends</dt><dd>{when(active.endsAt)}</dd></div></dl></>:<p className="admin-empty">No campaign is active.</p>}</section>
  <form className="admin-panel admin-form" action="/admin/actions" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="action" value="campaign.save"/><div><p className="eyebrow">New version</p><h2>Update future economics</h2><p>Enter whole cents. Saving deactivates the current version and creates a new immutable campaign record.</p></div><div className="admin-field-grid"><label>Friend incentive <span>cents</span><input required name="friendIncentiveMinor" type="number" min="0" max="100000000" step="1" defaultValue={active?.friendIncentiveMinor??0}/></label><label>Referrer cash reward <span>cents</span><input required name="referrerRewardMinor" type="number" min="0" max="100000000" step="1" defaultValue={active?.referrerRewardMinor??0}/></label><label>Holding period <span>days</span><input required name="holdingPeriodDays" type="number" min="0" max="3650" step="1" defaultValue={active?.holdingPeriodDays??0}/></label><label>Campaign status<select name="active" defaultValue={active?.active?"true":"false"}><option value="true">Active</option><option value="false">Paused</option></select></label></div><label className="admin-confirm"><input required type="checkbox" name="confirmation" value="SAVE_CAMPAIGN"/><span>I understand this changes the offer for new referrals only.</span></label><button className="button button-dark" type="submit">Publish campaign version</button></form></div>
  <section className="admin-panel admin-table-panel"><div className="admin-panel-heading"><div><p className="eyebrow">History</p><h2>Campaign versions</h2></div></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Version</th><th>Status</th><th>Friend</th><th>Referrer</th><th>Holding</th><th>Created</th></tr></thead><tbody>{data.campaigns.map(row=><tr key={row.id}><td data-label="Version"><strong>v{row.version}</strong><small>{row.name}</small></td><td data-label="Status"><Status value={row.active?"ACTIVE":"INACTIVE"}/></td><td data-label="Friend">{formatEuro(row.friendIncentiveMinor)}</td><td data-label="Referrer">{formatEuro(row.referrerRewardMinor)}</td><td data-label="Holding">{row.holdingPeriodDays} days</td><td data-label="Created">{when(row.createdAt)}</td></tr>)}</tbody></table></div></section>
  </>}

function Referrals({data,filters,csrfToken}:{data:FounderDashboardData;filters:FounderFilters;csrfToken:string}){return <><Header eyebrow="Referrals" title="Referral directory" copy={`${data.referralCount} operational records with snapshotted economics and lifecycle history.`}/><form className="admin-filterbar" method="get"><input type="hidden" name="tab" value="referrals"/><label>Search<input name="search" defaultValue={filters.search} placeholder="Referral or privacy-safe reference"/></label><label>State<select name="status" defaultValue={filters.referralStatus??"ALL"}><option value="ALL">All states</option>{Object.keys(stateLabels).filter(key=>!["REQUESTED","OPEN","INVESTIGATING","APPROVED"].includes(key)).map(key=><option key={key}>{key}</option>)}</select></label><label>Campaign<select name="campaign" defaultValue={filters.campaignId??""}><option value="">All campaigns</option>{data.campaigns.map(row=><option value={row.id} key={row.id}>v{row.version} · {row.name}</option>)}</select></label><label>From<input type="date" name="from" defaultValue={filters.from?.slice(0,10)}/></label><label>To<input type="date" name="to" defaultValue={filters.to?.slice(0,10)}/></label><button className="button button-soft" type="submit">Apply filters</button></form>
  <section className="admin-panel admin-table-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Referral</th><th>People</th><th>Economics</th><th>State</th><th>Created</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{data.referrals.map(row=><tr key={row.id}><td data-label="Referral"><strong>#{short(row.id)}</strong><small>{row.publicAttributionId.slice(0,18)}…</small></td><td data-label="People"><strong>{row.referrerReference}</strong><small>{row.referredReference}</small></td><td data-label="Economics"><strong>{formatEuro(row.referrerRewardMinor)} reward</strong><small>{formatEuro(row.friendIncentiveMinor)} friend · v{row.campaignVersion}</small></td><td data-label="State"><Status value={row.status}/>{row.fraudStatus?<small>Review: {displayState(row.fraudStatus)}</small>:null}</td><td data-label="Created">{when(row.createdAt)}</td><td data-label="Action"><Link className="admin-row-link" href={searchHref("referrals",{referral:row.id,search:filters.search,status:filters.referralStatus})} aria-label={`Open referral ${short(row.id)}`}>Open</Link></td></tr>)}</tbody></table></div>{!data.referrals.length?<p className="admin-empty">No referrals match these filters.</p>:null}<div className="admin-pagination"><span>Page {data.referralPage} of {data.referralPages}</span><div>{data.referralPage>1?<Link href={searchHref("referrals",{page:data.referralPage-1,search:filters.search,status:filters.referralStatus,campaign:filters.campaignId})}>Previous</Link>:null}{data.referralPage<data.referralPages?<Link href={searchHref("referrals",{page:data.referralPage+1,search:filters.search,status:filters.referralStatus,campaign:filters.campaignId})}>Next</Link>:null}</div></div></section>
  {data.selectedReferral?<ReferralDetailPanel referral={data.selectedReferral} csrfToken={csrfToken}/>:null}</>}
function ReferralDetailPanel({referral,csrfToken}:{referral:NonNullable<FounderDashboardData["selectedReferral"]>;csrfToken:string}){return <section className="admin-panel admin-detail-panel"><div className="admin-panel-heading"><div><p className="eyebrow">Referral #{short(referral.id)}</p><h2>Lifecycle & financial history</h2></div><Link href="/admin?tab=referrals">Close</Link></div><div className="admin-detail-summary"><div><span>Current state</span><Status value={referral.status}/></div><div><span>Reward snapshot</span><strong>{formatEuro(referral.referrerRewardMinor)}</strong></div><div><span>Friend snapshot</span><strong>{formatEuro(referral.friendIncentiveMinor)}</strong></div><div><span>Campaign</span><strong>v{referral.campaignVersion}</strong></div></div><div className="admin-detail-columns"><div><h3>Lifecycle</h3><ol className="admin-timeline">{referral.events.length?referral.events.map(event=><li key={event.id}><span/><div><strong>{displayState(event.toStatus)}</strong><small>{event.source} · {when(event.occurredAt,true)}</small></div></li>):<li><span/><div><strong>{displayState(referral.status)}</strong><small>Current persisted state</small></div></li>}</ol></div><div><h3>Ledger entries</h3>{referral.ledger.length?referral.ledger.map(entry=><div className="admin-ledger-row" key={entry.id}><span><strong>{entry.type}</strong><small>{entry.status} · {when(entry.createdAt,true)}</small></span><strong>{formatEuro(entry.amountMinor)}</strong></div>):<p className="admin-empty">No ledger entries for this referral.</p>}<h3>Fraud flags</h3>{referral.flags.length?referral.flags.map(flag=><div className="admin-ledger-row" key={flag.id}><span><strong>{displayState(flag.type)}</strong><small>{when(flag.createdAt,true)}</small></span><Status value={flag.status}/></div>):<><p className="admin-empty">No fraud flags.</p><details className="admin-action-disclosure"><summary>Add manual review flag</summary><form action="/admin/actions" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="action" value="fraud.flag"/><input type="hidden" name="referralId" value={referral.id}/><label>Reason<select name="type"><option value="MANUAL_FLAG">Manual flag</option><option value="SELF_REFERRAL">Self referral</option><option value="DUPLICATE_REFERRED_USER">Duplicate referred user</option><option value="SAME_DEVICE">Same device</option><option value="SUSPICIOUS_IP">Suspicious IP</option><option value="HIGH_VELOCITY">High velocity</option></select></label><button className="button button-soft">Send to review</button></form></details></>}</div></div></section>}

function Payouts({data,filters,csrfToken}:{data:FounderDashboardData;filters:FounderFilters;csrfToken:string}){return <><Header eyebrow="Payouts" title="Manual payout queue" copy="Send the bank transfer outside pH7 Refer, then record completion once. Mark Paid posts the immutable ledger debit atomically."/><form className="admin-filterbar admin-filterbar-compact" method="get"><input type="hidden" name="tab" value="payouts"/><label>Status<select name="payoutStatus" defaultValue={filters.payoutStatus??"ALL"}><option value="ALL">All payouts</option><option value="REQUESTED">Requested</option><option value="PAID">Paid</option><option value="REJECTED">Rejected</option><option value="CANCELLED">Cancelled</option></select></label><button className="button button-soft">Apply</button></form><section className="admin-panel admin-table-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Patient</th><th>Amount</th><th>Destination</th><th>Requested</th><th>Status / action</th></tr></thead><tbody>{data.payouts.map(row=><tr key={row.id}><td data-label="Patient"><strong>{row.referrerReference}</strong><small>#{short(row.id)}</small></td><td data-label="Amount"><strong>{formatEuro(row.amountMinor)}</strong><small>{formatEuro(row.availableBalanceMinor)} ledger balance</small></td><td data-label="Destination">{row.accountMask}</td><td data-label="Requested">{when(row.requestedAt,true)}</td><td data-label="Status / action">{row.status==="REQUESTED"?<details className="admin-action-disclosure"><summary>Review</summary><form action="/admin/actions" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="action" value="payout.paid"/><input type="hidden" name="payoutId" value={row.id}/><p>Confirm only after the manual transfer of <strong>{formatEuro(row.amountMinor)}</strong> to {row.accountMask} has completed.</p><label className="admin-confirm"><input required type="checkbox" name="confirmation" value="MARK_PAID"/><span>The transfer has been sent and verified.</span></label><button className="button button-dark">Mark paid</button></form></details>:<><Status value={row.status}/>{row.paidAt?<small>{when(row.paidAt,true)}</small>:null}</>}</td></tr>)}</tbody></table></div>{!data.payouts.length?<p className="admin-empty">No payout requests match this filter.</p>:null}</section></>}

function Fraud({data,filters,csrfToken}:{data:FounderDashboardData;filters:FounderFilters;csrfToken:string}){return <><Header eyebrow="Fraud" title="Review queue" copy="Deterministic flags and founder decisions. No inferred or invented risk scores."/><form className="admin-filterbar admin-filterbar-compact" method="get"><input type="hidden" name="tab" value="fraud"/><label>Status<select name="fraudStatus" defaultValue={filters.fraudStatus??"ALL"}><option value="ALL">All flags</option><option value="OPEN">Open</option><option value="INVESTIGATING">Investigating</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><button className="button button-soft">Apply</button></form><section className="admin-panel admin-table-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Flag</th><th>Referral</th><th>Evidence</th><th>Created</th><th>Resolution</th></tr></thead><tbody>{data.fraudFlags.map(flag=><tr key={flag.id}><td data-label="Flag"><strong>{displayState(flag.type)}</strong><small>#{short(flag.id)}</small></td><td data-label="Referral"><Link href={searchHref("referrals",{referral:flag.referralId})}>#{short(flag.referralId)}</Link></td><td data-label="Evidence">{Object.keys(flag.detail).length?<small>{Object.entries(flag.detail).map(([key,value])=>`${key}: ${String(value)}`).join(" · ")}</small>:<small>No additional evidence stored</small>}</td><td data-label="Created">{when(flag.createdAt,true)}</td><td data-label="Resolution">{["OPEN","INVESTIGATING"].includes(flag.status)?<details className="admin-action-disclosure"><summary><Status value={flag.status}/></summary><form action="/admin/actions" method="post"><input type="hidden" name="csrfToken" value={csrfToken}/><input type="hidden" name="action" value="fraud.resolve"/><input type="hidden" name="flagId" value={flag.id}/><label>Decision<select name="decision" defaultValue="INVESTIGATING"><option value="INVESTIGATING">Keep investigating</option><option value="APPROVED">Approve referral</option><option value="REJECTED">Reject referral</option></select></label><label className="admin-confirm"><input required type="checkbox" name="confirmation" value="RESOLVE_FLAG"/><span>Record this audited decision.</span></label><button className="button button-dark">Save decision</button></form></details>:<><Status value={flag.status}/>{flag.resolvedAt?<small>{when(flag.resolvedAt,true)}</small>:null}</>}</td></tr>)}</tbody></table></div>{!data.fraudFlags.length?<p className="admin-empty">The review queue is clear.</p>:null}</section></>}

function Audit({data,filters}:{data:FounderDashboardData;filters:FounderFilters}){return <><Header eyebrow="Audit" title="Founder audit trail" copy="Append-only security, campaign, payout and fraud operations. Sensitive credentials and bank data are excluded."/><form className="admin-filterbar admin-filterbar-compact" method="get"><input type="hidden" name="tab" value="audit"/><label>Search<input name="auditSearch" defaultValue={filters.auditSearch} placeholder="Action or entity"/></label><button className="button button-soft">Search</button></form><section className="admin-panel admin-table-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>Safe change metadata</th></tr></thead><tbody>{data.audit.map(event=><tr key={event.id}><td data-label="Timestamp">{when(event.createdAt,true)}</td><td data-label="Actor">{event.actor}</td><td data-label="Action"><strong>{event.action.replaceAll("_"," ")}</strong></td><td data-label="Entity">{event.subjectType}<small>#{short(event.subjectId)}</small></td><td data-label="Metadata">{event.beforeData||event.afterData?<details className="admin-audit-details"><summary>View change</summary>{event.beforeData?<div><span>Before</span><code>{JSON.stringify(event.beforeData)}</code></div>:null}{event.afterData?<div><span>After</span><code>{JSON.stringify(event.afterData)}</code></div>:null}</details>:<span className="admin-muted">No displayable metadata</span>}</td></tr>)}</tbody></table></div>{!data.audit.length?<p className="admin-empty">No audit events match this search.</p>:null}</section></>}

function navIcon(tab:FounderSection){return tab==="overview"?"⌂":tab==="campaigns"?"◫":tab==="referrals"?"↗":tab==="payouts"?"€":tab==="fraud"?"◇":"≡"}
function resultMessage(value:string){return value==="campaign-saved"?"Campaign version published. New referrals will use the updated economics.":value==="payout-paid"?"Payout marked paid and its immutable ledger debit recorded.":value==="flag-created"?"Referral moved into review.":value==="flag-resolved"?"Fraud decision recorded in the audit trail.":"Operation completed."}
